### ISSUE TITLE
Cli connect's to the wrong endpoint

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#120]
If I get more than one Endpoints on the commandline, sometimes a connection is established to the wrong endpoint

**Comment by polybassa** [comment]
the std::set sort's our endpoints by their ip-adress. 
I add a second methode which print's out the whole mIpTable content with the right index. We should not use the output from the Broadcastreceiver thread for the selection of an endpoint.

**Comment by bruenn** [comment]
we should but we have to use an ordered set with the right associated index

2013/4/22 polybassa notifications@github.com

**Comment by polybassa** [comment]
fixed with commit: 103176f
