### ISSUE TITLE
Add possibility to configurate the WLAN module as stand alone soft AP

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#124]

**Comment by bruenn** [comment]
Wie bitte? Das sollten wir auf gar keinen fall tun!

**Comment by polybassa** [comment]
Wieso? Mein Kumpel zum Beispiel hatte nur wep bei sich zu Hause und konnte wegen seines repeaters nicht auf wpa wechseln. 

Wenn wir wep nicht unterstützen sollten wir aber den soft-ap Mode, wie du schon vorgeschlagen hattest, anbieten

Am 27.04.2013 um 20:12 schrieb tawarisch notifications@github.com:

**Comment by bruenn** [comment]
Ja Soft-AP ist in Ordnung. Aber WEP Verschlüsselung ist wie Autofahren ohne Gurt. Kann man machen, im besten Fall wacht man dann nach nem Unfall wieder auf aber erfährt, das die Krankenversicherung die Bezahlung der Behandlung verweigert.
http://de.wikipedia.org/wiki/Wired_Equivalent_Privacy
http://www.heise.de/security/meldung/WEP-Verschluesselung-von-WLANs-in-unter-einer-Minute-geknackt-164971.html
Ach ja der artikel ist schon 6 Jahre alt!!!
