### ISSUE TITLE
Exception: ECONNRESET 

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#141]
When working with Wifly in SoftAP mode it happens very often, that no tcp connection is available anymore.
All commands send to the firmware report an "mSock.send() failed exception", debugging shows that send() failed with errno == ECONNRESET. All attemps to connect directly via telnet to wifly fail, too! A power down and reconnect brings everything back.

Affected Wifly firmware 2.45 and 4.00, so an update is not an option. Since I saw this only when working in SoftAP mode, I hope it is a bug only there and we can safetly operate in client mode. Further investigation should be done.

**Comment by bruenn** [comment]
Client mode with Firmware 4.00 works stable. We should deprecate SoftAP mode until a new firmware proved to be stable in SoftAP mode.
SoftAP is already flagged "deprecated" in Android user interface

**Comment by polybassa** [comment]
Did you observe this bug again, since we add the Rn-171 Parameter set comm idle <xxx>?
Maybe the Rn-171 reserved to much resources for zombie connections and so you get the error.

**Comment by bruenn** [comment]
Didn't observed the bug for over one year with Fw >= 4.00 -> closing
