### ISSUE TITLE
Telnet-Configuration issue, Special chars "!" etc

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#151]
Die SSID der FritzBox war "FRITZ!Box Fon WLAN 7320"

Dummerweise verträgt unser Modul das "!" nicht.
Sobald über Telnet das ! gesendet wird, hängt sich das Modul auf.

Die gute Nachricht ist aber:

Ich habe die Web-App des Moduls zum laufen gebracht, und erstaunlicherweise funktioniert die ziemlich gut.
Sogar so gut, das man über die Web-App die Sonderzeichen in der SSID eingeben kann, ohne das es zu einem Crash kommt.

Wir sollten uns beim nächsten Treffen umbedingt einen klaren Ablauf für die initiale Einrichtung beim Kunden überlegen.

Zu klären wären folgende Themen.
- Konfiguration ab Werk
- Konfigurationsablauf beim Kunden, initial
- Konfigurationsablauf beim Kunden, bei Umzug etc.
- Update-Möglichkeiten der Parameter von der App aus (für uns)

**Comment by bruenn** [comment]
Mit fällt gerade was ein. Bist du sicher das es das Modul ist? ! Müsste das erste Ersatz Zeichen in unserer Lib sein vielleicht habe ich da doch einen Fehler drin

**Comment by polybassa** [comment]
Ich hab den Fehler hauptsächlich mit dem Kommandozeile über Telnet direkt entdeckt. Dort ist dann die Kommunikation mit dem Modul abgebrochen, und nur durch einen Neustart konnte das Modul wieder erreicht werden

**Comment by polybassa** [comment]
ToDo: alle Zeichen testen und RQ an Microchip
Für uns: Ungültige Zeichen verbieten

**Comment by polybassa** [comment]
Hi, ich hab heute nochmals versucht den Fehler nachzustellen. Dabei habe ich alle möglichen Sonderzeichen als SSID eingegeben. 
Hat jedoch alles zu keinem Absturz geführt.
Aber mir ist Aufgefallen, das die String-Replace Routine im Telnet-Proxy nicht richtig arbeitet.
Kannst du dir die Routine nochmals ansehen, und überprüfen.
Wenn ich versuche die SSID: 
FRITZ!Box Fon WLAN 7320 
mit dem Telnetproxy einzugeben, erhalte ich diesen String im RN-171 Modul 
FRITZ!Box"Fon"WLAN"7320

Außerdem ist mir aufgefallen, das das Replacecharacter im RN-171 nach einem Boot in den Konfigurations-Soft-Ap auf 0 gesetzt wird. Vielleicht müssen wir da zuerst das Kommando set opt replace <HEX> senden, bevor wir die SSID übertragen. So ist sichergestellt, das das ReplceCharacter den richtigen Wert hat

**Comment by bruenn** [comment]
Hi Nils,
ich kann das bestätigen. Und schaue jetzt mal woran es liegt. Ich denke 
"SetReplaceChar" funktioniert nicht richtig.
Hoffentlich bei uns und nicht im Modul!
Gruß,
Patrick

**Comment by bruenn** [comment]
Also es liegt daran, dass SetReplaceChar sowas hier erzeugt:  >set opt replace "< laut doku müsste es aber so lauten: >set opt replace 0x22<
Ich werde das mal anpassen
