### ISSUE TITLE
use unique_ptr inside of WyLight::Script

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#157]
right now we use bare pointers and hope we catch all memory leaks. A unique_ptr would be nice but showed some trouble.
maybe there is a lack in the design of WyLight::Script which we can fix later.

**Comment by polybassa** [comment]
Wie sieht der Fehler bei dem unique_ptr aus?

**Comment by bruenn** [comment]
Naja das hat was mit der nicht kopierbarkeit vom unique_ptr zu tun. in 
der verfluchten std::list werden irgendwann (wann weiss ich nicht genau 
wegen den ellenlangen template fehlermeldungen) kopien der elemente 
gemacht und genau das geht nicht, wenn die elemente unique_ptr sind.
ich muss mal herausfinden, wann genau er mit dem kopieren anfängt, aber 
ich will mich jetzt erstmal auf was anderes konzentrieren. da wir die 
pointer nur genau einmal hinzufügen und nur genau dann löschen wenn das 
script gelöscht wird ist das memory management einfach und da riskiere 
ich jetzt mal nackte pointer. das ding ist ich bin schon genau zwei tage 
an dem problem und will jetzt mal weiter kommen.

**Comment by polybassa** [comment]
should be done with commit f21ea26
