### ISSUE TITLE
Library: save wlan config fails

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#170]
I observed that changing the wlan config fails very often with the message: _BAD CONFIG_. To repair this a manual "factory RESET" is necessary.
I suggest we add a "factory RESET" in front of our WiflyControl::ConfSetDefaults() function.
This should be done together with a refactoring of RN171_DEFAULT_PARAMETERS, RN171_BASIC_PARAMETERS and RN171_SOFT_AP_DEFAULT_PARAMETERS.
All comman parameters should move into DEFAULT and BASIC and SOFT_AP should only contain values that are different.
This can be implemented in a way that BASIC and SOFT_AP aggregate the values from DEFAULT, this will only increase memory redundancy and not code redundancy.
We should rename BASIC to CLIENT to clearify its use. (right now it isnt used!)

**Comment by polybassa** [comment]
we have to be careful with the parameters. Current DEFAULT is used for Client configuration. BASIC is used from the startupManager. Here we should not override parameters which are specific for SoftAP oder Client mode.
At the initial Configuration we can send factory RESET. After this we send the specific parameters for CLIENT or SOFTAP.
In the startup manager we can not use factory RESET. So I need a configuration with some default parameters for the startup manager.

**Comment by polybassa** [comment]
fixed with commit ebe26c0
Now we do a factory reset before we transfer the configuration parameters
