### ISSUE TITLE
Sync kann eingespart werden

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#28]
Bei Befehlen des Bootloaders, bei dem der sehr viele Befehle nacheinander gesendet werden, muss nicht vor jedem senden Syncronisiert werden.

-> enorme Zeitersparniss, gerade bei erase_flash

**Comment by bruenn** [comment]
should be fixed with merge #29 and #30

**Comment by polybassa** [comment]
Can we support this feature for read_flash and write_flash, too?
