### ISSUE TITLE
SetFade starts Run!

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#34]
SetFade startet den Run modus.
Das tritt bei mir sehr häufig auf. Und sieht nach nem Bufferoverflow aus.nachvollziehbar gerade nur auf dem Simulator. Ich habe das aber auch schon die gestern und vorgestern auf der echten hardware gesehen, dass der pic nach nem fade verrückt spielt

**Comment by polybassa** [comment]
Den Bug konnt ich auch schon bei der Hardware beobachten.
