### ISSUE TITLE
gLedBuf.led_array is in reverse order

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#36]
gLedBuf.led_array is in reverse order the led values are stored as:

B31, G31, R31, B30, G30, R30, ... B0, G0, R0

This is because void SPI_SendLedBuffer() starts reading from array[0] not arra[NUM_OF_LEDS *3 -1]
In different places in the code we have to do keep in mind the reverse order. This might be okay since we know it. but in my opinion it would be much clearer  to have an array like this:
R0, G0, B0, ... R31, G31, B31.

**Comment by polybassa** [comment]
check host to network byteorder of adress

**Comment by bruenn** [comment]
?
Am 03.02.2013 21:32 schrieb "polybassa" notifications@github.com:

**Comment by polybassa** [comment]
Roli hat mir folgendes Verhalten beschrieben (siehe Video), wenn er die Adressbits der Reihe nach von 0 auf 1 setzt. Ich hätte dieses Verhalten dem Issue #36 zugeordnet. Der Kommentar sollte nur als Erinnerung sein, dass ich die Adressbytes nach einem Fix überprüfe.

**Comment by polybassa** [comment]
@tawarisch: Please check if we have to reverse the gLedBuf.led_array byteorder too, or if the led_array and the address byteorder is fine now.

**Comment by bruenn** [comment]
everything looks fine, now:
on commandline "setfade 1 ff 0" works intuitive for me: it sets the the first led on strip to blue
you can argue on that but i like it that way. set first led to red would be "setfade 1 ff0000 0"
--> i close this issue
