### ISSUE TITLE
Change in CMDBuilder

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#38]
Hi Patrick, bitte schau dir mal meinen letzten commit an. 

Ich bin mir nicht sicher ob meine änderung noch irgendwelche nebeneffekte hat.

**Comment by bruenn** [comment]
_old_commandstorage_ lässt sich nicht mehr kompilieren

Am 23. November 2012 15:13 schrieb polybassa notifications@github.com:

**Comment by polybassa** [comment]
hab ich hoffentlich gerade gefixt,

make test, x86_client und pic konnte ich bei mir bauen.

Des nächste mal mach ichs in nem Branch… sorry.

Gruß Nils
