### ISSUE TITLE
test errormessages in wifly control

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#44]
Teste ob die Errormeldungen richtig angezeigt werden
Unit-Test für WiflyControl bei dem die Firmware mit abgetestet wird.

**Comment by bruenn** [comment]
Lets call it integration test to keep it separated from out unittests. the difference would be:

# UNITTEST
- require only a pc
- tests each software module isolated from its common environment
- todays "make test"
- files are named \* _ut.c*

# INTEGRATIONTEST
- depends on real hw, too
- tests multiple software parts and their interaction, maybe the whole system
- maybe "make integration" or "make test_it"
- we can name them \* _it.c*

As a further step we can think of a completed test loop where we connect the SPI bus of the pic with something like the http://nanorivertech.com/viperboard.html and then we can run full automated long term tests which test our system nearly to the end.

**Comment by bruenn** [comment]
i think we can close this, you already added the WiflyControlNoThrow_ut.cpp
