### ISSUE TITLE
change DEBUG compilerflag for Firmware and WiflyControl object 

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#63]
Xcode use the flag DEBUG too, 

so we have to change the code in DEBUG so that this code run's on iOS, 
or we use another flag for DEBUG in the Firmware and in WiflyControl

**Comment by rlindner** [comment]
Seems like including `#include <iostream>` in ComProxy.cpp works, so we might use the same flag name.

**Comment by bruenn** [comment]
Compiler switches should be used very rarely and not all over the code. Like described in the wiki(https://github.com/polybassa/Wifly_Light/wiki/Compiler-Swichtes) we want to keep the number of different switches low, too.

All of this code blocks in ComProxy and other places like:
#ifdef DEBUG
    printf("a oldschool printf trace message\n");
    std::cout << "a trace message using streams\n";
#endif

should be replaced with something like this:
Trace("your trace message");

this keeps the code clean and easier to read.

The different behavior for debug/release and different platforms is then implemented only in one place like trace.h. Only there you have to think of platform and build specific implementations which would look like:

// this is pseudo code, Iam sure it wont nearly compile!
#ifdef DEBUG
#ifdef IOS
    #include <stdio.h>
    #define Trace(...) fprintf(cout, **VA_ARGS**);
#elif OS_ANDROID
    #include <System>
    #define Trace(...) System.Log(**VA_ARGS**);
#else
    #include <stdio.h>
    #define Trace(...) printf(**VA_ARGS**);
#endif
#else
//remove trace code in release mode
#define Trace(...)
#endif 

So don't introduce new switches -> replace the existing #ifdef DEBUG code blocks with one of our trace macros and adjust the macro implementation for your platform if necessary. Always try to use as less #ifdef stuff as necessary and use platform independent code as much as possible.

**Comment by polybassa** [comment]
i think we can close this issue
