### ISSUE TITLE
Implement history function for cli.bin

### ISSUE THREAD

**Issue by rlindner** [polybassa/WyLight#64]
Would it be possible to implement an bash-like history function in client.bin so you can navigate to previously used commands by arrow up/down?

**Comment by polybassa** [comment]
So wie unsere Commandline Tool implementiert ist, haben wir (so wie ich das sehe) keine Möglichkeit ohne größere Architekturänderung eine Input-History einzubauen. 

Ich habe mir mal die GNU Readline Library für diese Funktion angesehen. 
Problem dabei ist nur, dass wir in der Hauptschleife für die Menüführung die komplette Zeile einlesen müssten.
Jedoch werden die Parameter wie Addresse und Farbe nicht von der Hauptschleife an die Unterfunktionen übergeben, sondern die Unterfunktionen rufen selbstständig cin >> xxx auf um Parameter einzulesen. 

Ließt die Hauptfunktion jetzt die komplette Zeile ein, haben die Unterfunktionen keine Möglichkeit ihre Parameter von dem Standart Input Stream zu bekommen.

@tawarisch: Fällt dir vielleicht noch eine Möglichkeit ein, wie wir eine History einfach implementieren könnten? Oder gibt es eine Möglichkeit einen String in den Standart Input Stream zurückzuschreiben, so dass dieser von cin eingelesen wird?

**Comment by bruenn** [comment]
Das Feature wäre bestimmt toll und ich ärger mich auch ständig, dass wir das nicht schon implementiert haben, aber momentan sehe ich einfach zu viele andere dinge, die wichtiger sind. Lass den Bug ruhig offen, wenn ich mal zeit habe schau ich es mir an, aber die nächsten tage würd ich nicht damit rechnen
