### ISSUE TITLE
random bug in ut_CommandIO_SendResponse

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#74]
I added a trace message to ut_CommandIO_SendResponse to get a memory dump of the random data which caused the test to fail.
To enable tracing add -DDEBUG option to the Makefile for the generic c unittest rule
This is the output i go in my case:

gpb@minime:~/workspace/Wifly_Light$ make clean && make CommandIO_ut.bin 
Crc error: 08 82 04 05 
Crc error: 3f 30 0f 04 
Crc error: 1a 0e 05 0f 
Crc error: 3f 30 0f 04 
Crc error: 1a 0e 05 0f 
CommandIO_ut.c:282: this random data killed the test:
62 00 22 27 08 67 e4 a4 20 dd 0a 14 8f 06 c4 a5 00 d8 7f ee bd f6 51 2d f9 f0 70 95 3e e2 0a 14 48 2d 3b 51 94 20 f5 b5 fd 00 c9 8d 06 8e 32 05 66 b2 f4 23 a8 45 50 a1 35 c0 36 73 a2 41 87 eb 6e c3 3c 02 e3 31 b7 e0 31 81 6d 38 0f a0 3d 75 52 31 98 fa 76 e8 9c ab a8 d2 1f 4a 13 a6 35 81 69 71 a3 bf e6 6a 0a 40 18 00 00 00 e0 94 19 40 60 4d a3 bf 04 76 0a 40 e0 94 19 40 00 10 02 40 18 00 00 00 0a 00 30 31 68 4d a3 bf 0c 88 04 08 80 c7 04 08 04 00 00 00 04 3f 3f c4 98 4d a3 bf c4 9e 04 08 04 00 00 00 88 4d a3 bf 87 4d a3 bf 0f e5 09 40 e0 94 19 40 0a 00 00 3f c4 ff 00 00 c4 c9 04 08 00 00 00 00 00 00 3a 3a c8 4d a3 bf 9f 9b 04 08 a0 c8 04 08 0f 00 00 00 00 00 00 00 00 00 00 00 f8 4d a3 bf 04 39 01 40 c8 4d a3 bf 46 9b 04 04 c7 3e 0b 40 00 00 00 00 f4 8f 19 40 7b 8d 04 
ERROR CommandIO_ut.c:283: ut_CommandIO_SendResponse() CHECK(success) failed
ut_CommandIO_SendResponse() run with 1 errors
           CommandIO_ut.c run 12 Tests ( 0 skipped |  1 errors)

**Comment by polybassa** [comment]
Should be fixed with commit 6044c12
