### ISSUE TITLE
Make calls to WiflyControl API thread-safe

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#75]
ComProxy and TelnetProxy are using the same TcpSocket. They shouldn't confuse each other. Even if this seperation wouldnt be in our architecture we have a problem, to callers calling WiflyControl functions at the same time. So we should make calls to all public WiflyControl thread and transaction save.

I thought about extracting the WiflyControl::Conf.. functions into some other class too, which would omit the problem of using the same socket for ComProxy and TelnetProxy, but it would only make sense with our current UI design see #59 , which might gets updated.

**Comment by bruenn** [comment]
This is not R1 relevant I think. When we stop using the member mCommandFrame, we should already be thread safe. We can never garantee to only have one connection to a led device, this has to be handled in the WLAN module, it shouldnt allow multiple connections at the same time.

**Comment by polybassa** [comment]
The WLan module allows only one connection at the same time. So it's not possible to init two WiflyControl objects with the same target
