### ISSUE TITLE
PIC FW crashes with "RedScreen"

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#89]
after some minutes suddenly the pic sets all LEDs to red and doesnt respond to further commands.
- reset button is without effect
- wlan modul still sends out broadcast messages
- power on reset is the only way to get it back running

affected device:
- patricks prototype (large pcb)

Iam not sure how to reproduce this error, maybe it is limited to my hw so i dont set the priority to R1

**Comment by polybassa** [comment]
Have you update your firmware in the last days? I did many changes to improve the stability of the firmware and to avoid a fatal-error crash

**Comment by bruenn** [comment]
Yes it is the latest firmware

**Comment by polybassa** [comment]
I had the same problem with the current fw. I expand the CommandBuffer in CommandIO.h after this change I had no red screen anymore.

**Comment by bruenn** [comment]
Kennst du auch die genaue ursache? Damit wir sicher sein können, das uns
kein fehler zwei mal passiert müssen wir versuchen einen unittest zu
schreiben der diesen fall simuliert, dann merken wir in zukunft sofort wenn
wir wieder ins gleiche problem laufen.
Am 23.03.2013 10:52 schrieb "polybassa" notifications@github.com:

**Comment by polybassa** [comment]
I did some changes in the CommandIO part. Now the input crawler get's more processor time from the main routine.
My changes are in commit 251bb05 . We have to watch our hardware, if a read screen appears again.

**Comment by polybassa** [comment]
a red screen crash is not possible now
