### ISSUE TITLE
PIC FW versioning

### ISSUE THREAD

**Issue by bruenn** [polybassa/WyLight#90]
We should add a version number to the pic firmware. It would be very helpful for future bugtracking with different in field firmware versions.
- At least it has to be readable at runtime
- it would by nice to read it directly from the hex file with a hex editor or something (don't has to be ascii, a binary hex code (1 byte) would be sufficient if its position in the file is fixed (maybe last byte)

**Comment by polybassa** [comment]
Done with commit 831e6c5
