### ISSUE TITLE
Create documentation for API

### ISSUE THREAD

**Issue by polybassa** [polybassa/WyLight#93]
Where we should document or code? 
In GitHub wiki or directly in the codefiles as comment?

**Comment by polybassa** [comment]
Maybe we can copy n paste something from here....

Zum Bootloader: 

```
Der Bootloader ermöglicht uns den Zugriff auf den Programm und den Datenspeicher des Microcontrollers. Über den Bootloader haben wir die Möglichkeit über WLAN neuen Programmcode oder Daten in
den Microcontroller zu laden, unabhängig von der eigentlichen Anwendung.

Wie kommt man in den Bootloadermodus?
    - beim Start des Mikrocontrollers: Wird die Taste BL am Mikrocontroller beim Einstecken des Steckers gedrückt, startet der Mikrocontroller automatisch in den Bootloadermodus (dieser Weg funktioniert IMMER und ist sozusagen         unsere letzte Chance den Bootloader zu starten, sollte mal ein grober BUG in der Firmware auf dem Mikrocontroller sein.
    - während des Betriebes
        - über den Taster BL
        - oder über die Funktion  bool FwStartBl(void);

Wie verlässt man den Bootloadermodus?
    über die Funktion  bool BlRunApp(void) const;

Vorgehen beim Programmieren der Firmware im Bootloadermodus.
    der Bootloader hat eine Auto-Start Funktion. Ist diese Autostart Funktion gesetzt, dann wird nach dem einstecken des Netzsteckers automatisch in den Bootloader gestartet. 
    Hintergrund zur Autostart-Funktion.
        Im normalen Betrieb ist die Autostart-Funktion deaktiviert, damit immer in die "Lampen" -Anwendung (Firmware) gestartet wird. 
        Vor einem Softwareupdate wird die Autostart-Funktion aktiviert. 
        Sollte jetzt beim Schreiben der Firmware in den Programmspeicher ein Fehler auftreten, dann kann es passieren das sich danach beim Starten der Firmware der Mikrocontroller aufhängt, oder unerwartet verhält.
        Bei einem Neustart (Ein- und Ausstecken) wird jedoch immernoch der Bootloader gestartet da der Autostart noch aktiviert ist. 

        Die Firmware setzt nach einer erfolgreichen Initialisierung automatisch den Bootloader Autostart auf deaktiviert. Das heißt, wenn die Firmware sich selbst erfolgreich initialisiert hat, dann startet der Mikrocontroller 
        danach automatisch in die Firmware und nicht in den Bootloader.

    Aus diesem Grund ist es wichtig, nach dem Programmieren einer neuen Firmware den Bootloadermodus über  bool BlRunApp(void) const; zu verlassen, weil nur so die Firmware die Möglichkeit bekommt,
    den Bootloader Autostart zu deaktivieren. Würde man beispielsweise versuchen die neue Firmware durch das Ein- und Ausstecken des Netzsteckers zu starten, würde man IMMER im Bootloader-Modus landen,
    da beim Schreiben einer neuen Firmware in den Controller die Bootloader Autostart Funktion aktiviert ist.
```

// ------------------------ Bootloader: Wichtige Methoden ------------------//

bool BlRunApp(void) const;
    zum Starten der Anwendung auf dem Mikrocontroller

bool BlProgramFlash(const std::string& Filename);
    zum Programmieren einer neuen Firmware in den Mikrocontroller

size_t BlReadInfo(BlInfo& info) const;
    zum Auslesen der Bootloaderinformationen, jedoch für dich vielleicht nur hilfreich um zu überprüfen ob der Mikrocontroller im Bootloader-Modus ist oder nicht.

Zur Firmware (oder Applikation):
    Die Firmware besitzt intern einen Ringspeicher der mit einer gewissen Intelligenz durch den "sogenannten" ScriptController erweitert wurde.
    Der ScriptCtrl nimmt alle deine Befehle die du sendest entgegen und arbeitet diese ab. Einige werden sofort abgearbeitet ( FwSetRtc oder FwStartBl, oder FwClearScript) andere benötigen zur Abarbeitung einige Zeit z.B. Wait oder    Fade.
    Diese Befehle wie (SetColor, SetFade oder SetWait) werden hintereinander abgearbeitet: D. H. die Befehle werden zuerst alle in den Ringspeicher geschrieben. Ist jetzt ein Befehl mit seiner Abarbeitung fertig, wird darauf der  
    nächste Ausgeführt, in der Reihenfolge, wie du die Befehle übermittelt hast.
    Möchtest du erzwingen, dass ein Befehl sofort aufgeführt wird, auch wenn ein anderer Befehl wie Fade oder Wait gerade läuft, kannst du den ScriptController über FwClearScript dazu bringen seine aktuelle Abarbeitung zu
    unterbrechen und seinen kompletten Speicher mit allen nachfolgenden Befehlen zu löschen.
    Sendest du sehr viele Befehle (derzeit max 63) hintereinander, während der Scriptcontroller gerade einen andernen sehr lange andauernden Befehl abarbeitet, kann es passieren dass der Ringspeicher voll wird. Darauf hin
    erhältst du dann nurnoch Fehlermeldungen bzw false als Rückantwort der Funktion. Hier schafft FwClearScript abhilfe.

```
Über die Loop Befehle kannst du mehrfach verschachtelte Schleifen in den Ringspeicher programmieren:
Beispiel:

    LoopOn
    Farbe Rot 
    Farbe Blau
    Warten
        LoopOn
        Farbe Grün
        Farbe Gelb
        Warten
        LoopOff ( 5 )
    Farbe Rot
    LoopOff ( 0 )

Die Ausführung dieses Beispiels würde jetzt so aussehen: 
    --> Leds Rot
    --> Leds Blau
    --> Wartezeit

    --> jetzt würde der Controller in eine Unterschleife springen
    --> Led Grün
    --> Led Gelb
    --> Warten
    --> diese Unterschleife wird jetzt noch 5 mal ausgeführt

    --> danach 
    --> Led Rot
    --> Die 0 des LoopOff Befehl signalisiert eine Endlosschleife. Der Controller würde jetzt wieder zum Anfang (erster LoopOn Befehl) springen und diese Komplette schleife mit Unterschleife endlos ausführen.

Derzeit kann der Ringspeicher 63 Befehle speichern (dazu zählen die Befehle SetColor, SetWait, SetFade, LoopOn und LoopOff. Alle anderen Befehle werden nicht gespeichert sondern direkt abgearbeitet)
Die maximale Schachtelungstiefe der Unterschleifen ist 4.
```

// ------------------------ Firmware: Wichtige Methoden ------------------//
bool FwClearScript(void);
        Löscht den Inhalt des Ringspeichers    

bool FwLoopOn(void);
    Signalisiert dem ScriptController den Anfang einer Schleife oder Unterschleife  

bool FwLoopOff(unsigned char numLoops);
        Signalisiert dem ScriptController das Ende einer Schleife oder Unterschleife. Über numLoops kannst du für die Anzahl der Durchläufe der aktuellen
    Schleife festlegen. 0 bedeutet Endlosschleife.

bool FwSetColor(unsigned long addr, unsigned long rgba);
    // ACHTUNG diesen Befehl nicht mehr verwenden, wird bald entfernt. Anstatt diesen Befehl lieber FwSetFade mit fadeTmms = 0 verwenden

bool FwSetColorDirect(unsigned char\* pBuffer, size_t bufferLength);
    Über diesen Befehl lassen sich direkt Werte für die Leds eingeben. Dieser Befehl wird nicht im Ringspeicher gespeichert. Anwendung: wenn Beispielsweise über
    ein Kommando viele Led's verschiedene Farben erhalten sollen. 
    Der Befehl ist für eine direkte Ansteuerung durch einen Client gedacht. 
    für pBuffer muss ein Array übergeben werden, welches die Länge NUM_OF_LED \* 3 hat (== ist aktuell 96).
    Ein kleineres oder größeres Array macht verursacht keinen Fehler, es werden nur nicht alle Led's angesteuert.
    Die Werte des Array werden von dem Controller direkt an die LED's weitergegeben.
    Wie die aktuelle Reihenfolge der Farbwerte ist weis ich leider gerade nicht. Am besten einfach mal ausprobieren.
    Das Muster der Farbwerte im Array ist immer: Rot Grün Blau Rot Grün Blau……… oder umgedreht.
    Dieser Befehl wird auch sofort abgearbeitet.

bool FwSetFade(unsigned long addr, unsigned long rgba, unsigned short fadeTmms, bool parallelFade);
    Dieser Befehl erzeugt einen Farbverlauf zur angegebenen Farbe, für alle Led's deren Adressbit 1 ist.
    Über das bool parallelFade kann das Verhalten des ScriptControllers verändert werden.
    Beispiel parallelFade = true: Kommt der ScriptController zu diesem Fade Befehl, wird dieser Abgearbeitet, das heißt die "Zielfarben" und die Zeitwerte für alle
        makierten LED's werden gesetzt. Jedoch wartet der ScriptController jetzt nicht, bis alle "Zielfarbwerte" erreicht sind, sonder springt direkt zum nächsten Befehl
        Hier kann jetzt ein weiterer FadeBefehl stehen, der sich auf andere Led's auswirkt, so kann ein Farbverlauf von verschiedenen LED's zu unterschiedlichen Zielfarben
        erzeugt werden. (die Farbverläufe laufen parallel ab)

```
Beispiel parallelFade = false: Hier wird der Befehl abgearbeitet sobald der Scriptcontroller den Befehl erreicht, jedoch hält der ScriptController nun bis alle Zielfarbwerte
    für ALLE Led's erreicht sind.

So kann ein Farbverlauf mehrerer Led's beispielsweise so einprogrammiert werden.
    Fade ff000000 Rot parallel 
    Fade 00ff0000 Grün parallel
    Fade 0000ff00 Blau parallel
    Fade 000000ff Gelb nicht-parallel

    Jetzt werden alle vier FadeBefehle gleichzeitig für verschiedene Leds zu unterschiedlichen Farben ausgeführt. Durch den Letzten Befehl der nicht-parallel ist
    hält der ScriptController bei diesem Befehl jetzt solange bis alle Fade-Befehle fertig sind.
```

bool FwSetWait(unsigned short waitTmms);
    Hält den ScriptController für den angegebenen Zeitwert an.

void FwAddColor(unsigned long addr, unsigned long rgba, unsigned char hour, unsigned char minute, unsigned char second);
    // NOCH NICHT IMPLEMENTIERT: NICHT VERWENDEN

void FwTest(void);
    Testfunktion: Erzeugt ein paar bunte Farben auf dem Ledstreifen (TestBild)

bool FwPrintCycletime(std::ostream& out);
    DEBUG-Funktion um Zykluszeiten einzelner Funktionen auszulesen

void FwPrintTracebuffer(std::ostream& out);
    DEBUG-Funktion um den Fehlerspeicher des Mikrocontrollers auszulesen

bool FwStartBl(void);
    Startet den Bootloader

bool FwSetRtc(struct tm\* timeValue);
    Setzt die Echtzeituhr in der Firmware auf die übergebene Zeit. Soll später für Weckerfunktionen genutzt werden.

bool FwGetRtc(struct tm\* timeValue);
    Gibt den aktuellen Zeitwert der Echzeituhr zurück.

bool FwPrintRtc(std::ostream& out);
    Wie oben, jedoch überflüssig
    //WIRD DEMNÄCHST GELÖSCHT

**Comment by bruenn** [comment]
First priority should be the code (header files). As we use doxygen style comments it would be possible to generate a doxygen html documentation very easily. I will do some research if it is possible to include doxygen html into github, which would be the high end solution. If that doesnt work i will provide the doxygen html on a webserver seperate webserver and set a link in the github wiki to that webpage.

**Comment by polybassa** [comment]
http://rickfoosusa.blogspot.de/2011/10/howto-use-doxygen-with-github.html

should work... I will check it again in a quite minute (after work)

**Comment by polybassa** [comment]
Have a look at: http://polybassa.github.com/Wifly_Light/
Not finished now, but its a beginning...
